import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const satoshi = localFont({
  src: [
    {
      path: '../public/font/Satoshi-Regular.otf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../public/font/Satoshi-Medium.otf',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../public/font/Satoshi-Bold.otf',
      weight: '700',
      style: 'normal'
    }
  ],
  variable: '--font-satoshi',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${satoshi.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
