export default function Home() {
  const testSection = [
    {
      title: 'Section 1',
      labelEdited:
        'As a front-end engineer, I have a solid understanding of front-end technologies, such as complex functionality, maintaining existing sites, debugging, and improving the user experience. I am also highly motivated and self-directed, with a strong work ethic and a constant desire to learn new skills to further improve my craft.'
    },
    {
      title: 'Section 2',
      label:
        'Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural her Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here.'
    },
    {
      title: 'Section 3',
      label:
        'Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural her Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here.'
    },
    {
      title: 'Section 4',
      label:
        'Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural her Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here.'
    },
    {
      title: 'Section 5',
      label:
        'Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural her Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here.'
    },
    {
      title: 'Section 6',
      label:
        'Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural her Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here.'
    },
    {
      title: 'Section 7',
      label:
        'Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural her Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here. Swap this for real content once the timing and spacing feel right. This first section usually sets the pace for everything after it, so it is worth spending extra time getting the reveal timing to feel natural here.'
    }
  ];

  return (
    <div className="relative flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
      <div className="bg-grid absolute inset-0 pointer-events-none" />
      <main className="flex flex-1 w-full max-w-4xl flex-col items-center px-16 bg-white dark:bg-black sm:items-start">
        {testSection.map((s, index) => (
          <section
            key={index}
            className="w-full py-32 border-t border-zinc-200 dark:border-white/10 first:border-t-0 first:pt-40"
          >
            <h2>{s.title}</h2>
            <p className="font-test-montserrat text-[15px] leading-loose font-medium">{s.label}</p>
            <p className="font-test-montserrat text-[15px] leading-loose font-medium">
              {s.labelEdited}
            </p>
          </section>
        ))}
      </main>
    </div>
  );
}
